
#nullable disable

namespace SeemsAPIService.Domain.Entities
{
    public class Job
    {
        public string JobNumber { get; set; }
        public string JobName { get; set; }
        public string Customer { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string ProjectManager { get; set; }
        public string Designer1 { get; set; }
        public string Designer2 { get; set; }
        public string Designer3 { get; set; }
        public string Library { get; set; }
        public string Fabrication { get; set; }
        public string DFXAnalysis { get; set; }
        public string QA { get; set; }
        public string CAM { get; set; }
        public string JOBID { get; set; }
        public string RequestRaisedBy { get; set; }
        public string Requestdate { get; set; }
        public string RequestAddressedBy { get; set; }
        public string RequestAddressedByTime { get; set; }
        public string EmployeeID { get; set; }
        public string Status { get; set; }
        public string pcbtool { get; set; }
        public string RequestRaisedByID { get; set; }
        public string RequestAddressedByID { get; set; }
        public string ProjectManagerID { get; set; }
        public string Designer1ID { get; set; }
        public string Designer2ID { get; set; }
        public string Designer3ID { get; set; }
        public string schtool { get; set; }
        public string designer4 { get; set; }
        public string designer5 { get; set; }
        public string designer6 { get; set; }
        public string designer7 { get; set; }
        public string designer8 { get; set; }
        public string designer9 { get; set; }
        public string designer10 { get; set; }
        public string designer11 { get; set; }
        public string designer12 { get; set; }
        public string designer13 { get; set; }
        public string designer14 { get; set; }
        public string designer15 { get; set; }
        public string designer16 { get; set; }
        public string designer17 { get; set; }
        public string designer18 { get; set; }
        public string designer19 { get; set; }
        public string designer20 { get; set; }
        public string designer4id { get; set; }
        public string designer5id { get; set; }
        public string designer6id { get; set; }
        public string designer7id { get; set; }
        public string designer8id { get; set; }
        public string designer9id { get; set; }
        public string designer10id { get; set; }
        public string designer11id { get; set; }
        public string customer1 { get; set; }
        public string designer12id { get; set; }
        public string designer13id { get; set; }
        public string designer14id { get; set; }
        public string designer15id { get; set; }
        public string designer16id { get; set; }
        public string designer17id { get; set; }
        public string designer18id { get; set; }
        public string designer19id { get; set; }
        public string designer20id { get; set; }
        public string customer2 { get; set; }
        public string customer3 { get; set; }
        public string customer4 { get; set; }
        public string customer5 { get; set; }
        public string customer6 { get; set; }
        public string customer7 { get; set; }
        public string customer8 { get; set; }
        public string customer9 { get; set; }
        public string customer10 { get; set; }
        public string customer1id { get; set; }
        public string customer2id { get; set; }
        public string customer3id { get; set; }
        public string customer4id { get; set; }
        public string customer5id { get; set; }
        public string customer6id { get; set; }
        public string customer7id { get; set; }
        public string customer8id { get; set; }
        public string customer9id { get; set; }
        public string customer10id { get; set; }
        public string sdg1 { get; set; }
        public string sdg2 { get; set; }
        public string sdg3 { get; set; }
        public string sdg4 { get; set; }
        public string sdg5 { get; set; }
        public string sdg6 { get; set; }
        public string sdg7 { get; set; }
        public string sdg8 { get; set; }
        public string sdg9 { get; set; }
        public string sdg10 { get; set; }
        public string sdg1id { get; set; }
        public string sdg2id { get; set; }
        public string sdg3id { get; set; }
        public string sdg4id { get; set; }
        public string sdg5id { get; set; }
        public string sdg6id { get; set; }
        public string sdg7id { get; set; }
        public string sdg8id { get; set; }
        public string sdg9id { get; set; }
        public string sdg10id { get; set; }
        public string hardwaremanager { get; set; }
        public string hardwaremanagerid { get; set; }
        public string efforts { get; set; }
        public string description { get; set; }
        public string level_status { get; set; }
        public string copyofcustomer { get; set; }
        public string BACKUP { get; set; }
        public string sitool { get; set; }
        public string thermaltool { get; set; }
        public string camtool { get; set; }
        public string mechanicaltool { get; set; }
        public string dfxtool { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string revisioncard { get; set; }
        public string revisioncard_jobnumber { get; set; }
        public string projectlocation { get; set; }
        public string projecttype { get; set; }
        public string billability { get; set; }
        public string Layout { get; set; }
        public string SI { get; set; }
        public string Thermal { get; set; }
        public string EMI_EML { get; set; }
        public string Procurement { get; set; }
        public string Assembly { get; set; }
        public float? TimeSpent_Lib { get; set; }
        public float? timespentfor_symbols { get; set; }
        public float? TimeSpentbydesigner { get; set; }
        public float? TimeSpent_QA { get; set; }
        public float? TimeSpent_CAM { get; set; }
        public string TotalTimeTakenHrs { get; set; }
        public string Billingstatus { get; set; }
        public string projectmode { get; set; }
        public string e_layout { get; set; }
        public string e_thermal { get; set; }
        public string e_symbols { get; set; }
        public string e_schematic { get; set; }
        public string e_emi_emc { get; set; }
        public string e_packaging { get; set; }
        public string e_pi { get; set; }
        public string e_mechanicals { get; set; }
        public string e_qa_mech { get; set; }
        public string e_qa_bom { get; set; }
        public string e_gerber { get; set; }
        public string e_postprocess { get; set; }
        public string e_routing { get; set; }
        public string e_constraints { get; set; }
        public string e_va { get; set; }
        public string e_valor { get; set; }
        public string e_others { get; set; }
        public string e_analysis { get; set; }
        public string e_software { get; set; }
        public string e_fpga { get; set; }
        public string e_sales { get; set; }
        public string e_hardware { get; set; }
        public DateTime? effortsupdateddate { get; set; }
        public string effortsupdatedbyid { get; set; }
        public string enquiryno { get; set; }
        public string obillingtype { get; set; }
        public DateTime? startdate1 { get; set; }
        public DateTime? enddate1 { get; set; }
        public string PI { get; set; }
        public string job_category { get; set; }
        public string hardwarejobno { get; set; }
        public string layoutjobno { get; set; }
        public string valueadditionjobno { get; set; }
        public string Jobstructure { get; set; }
        public string Parentjobname { get; set; }
        public string Jobtype { get; set; }
        public string Parentjobnumber { get; set; }
        public string packaging { get; set; }
        public string MECHANICALS { get; set; }
        public string Placement { get; set; }
        public string routing { get; set; }
        public string postprocess { get; set; }
        public string post_si { get; set; }
        public string pre_si { get; set; }
        public string thermalanalysis { get; set; }
        public string pianalysis { get; set; }
        public string emi_emc { get; set; }
        public string dfaanalysis { get; set; }
        public string hyperlynxdrc { get; set; }
        public string fabricatin_taskclose { get; set; }
        public string procurement_taskclose { get; set; }
        public string assembly_taskclose { get; set; }
        public string hyperlynxdrc_chk { get; set; }
        public string presi { get; set; }
        public string postsi { get; set; }
        public uint? serialno { get; set; }
        public string training { get; set; }
        public uint? version { get; set; }
        public string invioce_flag { get; set; }
        public uint? No_workingdays { get; set; }
        public uint? billingtandm { get; set; }
        public uint? adv_amount { get; set; }
        public uint id { get; set; }
        public string jobapproval { get; set; }
        public string costctrans { get; set; }
        public string transpm { get; set; }
        public uint OnsiteCount { get; set; }
        public uint? SeqNo { get; set; }
        public uint? mailCount { get; set; }
        public string paymentTerm { get; set; }
        public string Tsheet_status { get; set; }
        public DateTime? Tsheet_date { get; set; }
        public string billingtype { get; set; }
        public int? ecoTime { get; set; }
        public string pitool { get; set; }
        public string EMItool { get; set; }
        public string LeadDesigner { get; set; }

        public string NPI { get; set; }
        public string designer21 { get; set; }
        public string designer22 { get; set; }
        public string designer23 { get; set; }
        public string designer24 { get; set; }
        public string designer25 { get; set; }
        public string designer26 { get; set; }
        public string designer27 { get; set; }
        public string designer28 { get; set; }
        public string designer29 { get; set; }
        public string designer30 { get; set; }
        public string designer21id { get; set; }
        public string designer22id { get; set; }
        public string designer23id { get; set; }
        public string designer24id { get; set; }
        public string designer25id { get; set; }
        public string designer26id { get; set; }
        public string designer27id { get; set; }
        public string designer28id { get; set; }
        public string designer29id { get; set; }
        public string designer30id { get; set; }
        public string VA { get; set; }
        public string e_footprintqc { get; set; }
        public string e_symbolqc { get; set; }
        public string e_Library3D { get; set; }
        public string OtherTool { get; set; }
        public string harddesign { get; set; }
        public string mechdesign { get; set; }
        public string e_harddesign { get; set; }
        public string e_mechdesign { get; set; }
    }
}
